# Deploy dfbaskin.com web site.

on:
  push:
    branches:
      - master

name: DeployDFBaskinWeb

jobs:
  deploy-dfbaskin-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: NPM Install
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Create Zip Deployment File
        uses: thedoctor0/zip-release@master
        with:
          filename: dfbaskin-web.zip
          directory: out

      - run: dir .
      - run: dir ./out
      - run: dir ${{ github.workspace }}

      # - name: Login to Azure
      #   uses: azure/login@v1.1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Azure CLI script
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az webapp deployment source config-zip \
      #         --resource-group ${{ secrets.WEB_SITE_RESOURCE_GROUP }} \
      #         --name dfbaskin-website \
      #         --src dfbaskin-web.zip
